# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarQuotation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('variation', models.FloatField()),
            ],
        ),
    ]
