# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('variation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EuroQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('variation', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='dollarquotation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
