from rest_api.Serializers.DollarQuotationSerializer import DollarQuotationSerializer
from rest_api.Serializers.EuroQuotationSerializer import *
from rest_api.Serializers.BitcoinQuotationSerializer import BitcoinQuotation